'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/organisms/Footer/Footer";
import HeaderWrapper from "../components/organisms/Header/HeaderWrapper";
import { WebVitals } from "../web-vitals";
import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "SFCC PRO",
//   description: "Generated by Pros",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
  const client = new ApolloClient({
    uri: "http://localhost:4000",
    cache: new InMemoryCache(),
  });
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{width:'100vw'}}>
      <ApolloProvider client={client}>
      <WebVitals />
      <HeaderWrapper/>
        {children}
        <Footer/>
      </ApolloProvider>
      </body>
    </html>
  );
}
