import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import Footer from "../components/organisms/Footer/Footer";
import HeaderWrapper from "../components/organisms/Header/HeaderWrapper";
import { WebVitals } from "../web-vitals";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "SFCC PRO",
	description: "Generated by Pros",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable}`}
				style={{ width: "100vw" }}
			>
				<WebVitals />
				<HeaderWrapper />
				{children}
				{(await draftMode()).isEnabled && (
					<>
						<VisualEditing />
						<DisableDraftMode />
					</>
				)}
				<Footer />
			</body>
		</html>
	);
}
