export default {
  name: "product",
  title: "Product",
  type: "document",
  fields: [
    { name: 'sku', type: 'string', title: 'SKU', readOnly: true },
    { name: 'productId', type: 'string', title: 'Product ID', readOnly: true},
    { name: 'name', type: 'string', title: 'Name' },
    { name: 'slug', type: 'slug', title: 'Slug', options: { source: 'name', maxLength: 96 } },
    { name: 'description', type: 'text', title: 'Description' },
    { name: 'categoryId', type: 'string', title: 'Category ID', readOnly: true },
    { name: 'price', type: 'number', title: 'Price', readOnly: true },
    { name: 'currency', type: 'string', title: 'Currency', readOnly: true},
    { name: 'isOnline', type: 'boolean', title: 'Is Online?', readOnly: true },
    { name: 'lastModified', type: 'datetime', title: 'Last Modified' },
    { name: 'variationAttributes', type: 'array', of: [{ type: 'string' }], title: 'Variation Attributes' , readOnly: true},
    { name: 'productKind', type: 'string', title: 'Product Kind', initialValue: 'master', readOnly: true },
    {
      name: 'variants',
      title: 'Variants',
      type: 'array',
      of: [{ type: 'reference', to: [{ type: 'variant' }] }], readOnly: true,
    },
    { name: "importedAt", type: "datetime", title: "Imported At" },
  ],
};
